name: Publish to surge.sh

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to bros-trading.surge.sh
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          domain: 'bros-trading.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
