name: Publish to surge.sh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16

      - name: Install Surge
        run: yarn global add surge

      - name: Build React App
        run: |
          yarn install # Install Dependencies
          CI=false yarn run build # CI=false to ignore warnings

      - name: Publish to surge.sh
        run:  surge ./build https://bros-trading.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
